### ISSUE TITLE
[Critical bug] Error: Nonexistent flag: --daemon-off

### ISSUE THREAD

**Issue by tuukkaviitanen** [mockoon/cli-action#1]
When running the latest mockoon/cli version (which seems to be 6.2.0 at the moment), --daemon-off is not a flag. This breaks the action completely. My environment is too new for older mockoon versions so I have not yet tested it with versions <6.

![image](https://github.com/mockoon/cli-action/assets/97726090/d42dc5e0-4e90-4a08-b8f1-3a3310fe4b84)

**Comment by tuukkaviitanen** [comment]
Seems that the flag was removed in 4.0.0: https://mockoon.com/releases/4.0.0/

**Comment by 255kb** [comment]
Thank you for reporting this. It completely slipped our mind during one recent release where we cleaned the flags removed in v4.0.0 (There were kept until v6.1.0, so the flag was ignored instead of throwing an error). 
You can now update the action to v2 and it will work.

**Comment by tuukkaviitanen** [comment]
> Thank you for reporting this. It completely slipped our mind during one recent release where we cleaned the flags removed in v4.0.0 (There were kept until v6.1.0, so the flag was ignored instead of throwing an error). 
> You can now update the action to v2 and it will work. 

My pleasure! You're doing great work! I'll be sure to try out the new version. Thanks!
